// FR-HOOK-0009 — ordered bootstrap manifest + prefix text
// Decoded from baseline agents/TEMP/old-gen-r2/core-claude/hooks/hooks.json

import type { BootstrapEntryRef } from '../types.js';

/**
 * The canonical ordered manifest of bootstrap document basenames.
 * Only present documents (those in the target's VFS/frames) are included — engine is content-agnostic.
 * The plugin-root entry is NOT in this list — it is appended separately (GT-3.4).
 * FR-HOOK-0009, GT-2.1
 */
export const BOOTSTRAP_MANIFEST_ORDER: ReadonlyArray<BootstrapEntryRef> = [
  { basename: 'plugin-files-mode' },   // both releases; first in the manifest (FR-HOOK-0009)
  { basename: 'bootstrap-alwayson' },  // r3-only; absent docs are skipped (FR-HOOK-0001)
  // The five below are r2-only: r3 consolidates all of them into the single
  // `bootstrap-alwayson` above, so in r3 every one of them is absent and skipped.
  { basename: 'bootstrap-core-policy' },
  { basename: 'bootstrap-execution-policy' },
  { basename: 'bootstrap-hitl-questioning' },
  { basename: 'bootstrap-guardrails' },
  { basename: 'bootstrap-rosetta-files' },
  // Index entries (positions 6 & 7 — included when includeIndexEntries is true)
  // These are virtual entries generated by pluginGenerateIndexes:
  { basename: '__rules_index__' },     // rules/INDEX.md
  { basename: '__workflows_index__' },  // workflows/INDEX.md (or commands/)
];

/**
 * The fixed manifest for the plugin-root entry (GT-3.4).
 * One per IDE target, decoded from baseline.
 */
export const CLAUDE_PLUGIN_ROOT_ENTRY = {
  command: `printf '%s' "{\\"hookSpecificOutput\\":{\\"hookEventName\\":\\"SessionStart\\",\\"additionalContext\\":\\"Rosetta Plugin Path: \${CLAUDE_PLUGIN_ROOT}\\"}}"`,
};

export const CODEX_PLUGIN_ROOT_COMMAND =
  `workspace_root="$PWD"; ` +
  `while [ "$workspace_root" != "/" ] && [ ! -f "$workspace_root/.agents/rules/plugin-files-mode.md" ]; do ` +
  `workspace_root="$(dirname "$workspace_root")"; ` +
  `done; ` +
  `if [ -f "$workspace_root/.agents/rules/plugin-files-mode.md" ]; then ` +
  `printf '%s' "{\\"hookSpecificOutput\\":{\\"hookEventName\\":\\"SessionStart\\",\\"additionalContext\\":\\"Rosetta Plugin Path: $workspace_root/.agents\\"}}"; ` +
  `fi`;

// Copilot needs additionalContext at BOTH top-level (Copilot CLI) AND nested in
// hookSpecificOutput (VS Code) — see docs/hooks/copilot.md, Bug 2.
//
// The install path is DELIBERATELY hardcoded rather than discovered at runtime: Copilot does not
// expose its own plugin path, and its hooks run in either standalone or plugin mode with only one
// firing per case. It is, however, SET-AWARE — parameterized on the spec's output folder name, so
// `qe-copilot` probes its own directory, and `core-copilot-light` probes `core-copilot-light`
// rather than (as it did while this was a literal) the unrelated `core-copilot`.
// Guard file: `.github/plugin/plugin.json`, not `commands/coding-flow.md` (hooks-architecture.md
// §1.5, §3 step 8). The marketplace manifest is emitted unconditionally by pluginCopy's manifest
// overlay for EVERY Copilot spec, at a location content-independent of any set split — unlike
// `commands/coding-flow.md`, which lives in the `workflows` set (not `core`) and made this probe
// a permanent no-op for every `core`-based Copilot plugin (FR-HOOK-0007). It is also, not
// coincidentally, the file this probe itself lives alongside in the output tree.
export const COPILOT_PLUGIN_ROOT_BASH = (destination: string): string =>
  `for base in "$HOME/.vscode/agent-plugins" "$HOME/.local/share/Code/agentPlugins"; ` +
  `do root="$base/github.com/griddynamics/rosetta/plugins/${destination}"; ` +
  `if [ -f "$root/.github/plugin/plugin.json" ]; then ` +
  `printf '%s' "{\\"additionalContext\\":\\"Rosetta Plugin Path: $root\\",\\"hookSpecificOutput\\":{\\"hookEventName\\":\\"SessionStart\\",\\"additionalContext\\":\\"Rosetta Plugin Path: $root\\"}}"; ` +
  `break; ` +
  `fi; ` +
  `done`;

export const COPILOT_PLUGIN_ROOT_POWERSHELL = (destination: string): string =>
  `$root = "$env:LOCALAPPDATA\\Code\\agentPlugins\\github.com\\griddynamics\\rosetta\\plugins\\${destination.replace(/\//g, '\\')}"; ` +
  `if (Test-Path "$root\\.github\\plugin\\plugin.json") { ` +
  `Write-Output ('{"additionalContext":"Rosetta Plugin Path: ' + $root + '","hookSpecificOutput":{"hookEventName":"SessionStart","additionalContext":"Rosetta Plugin Path: ' + $root + '"}}') ` +
  `}`;

/**
 * The cursor plugin-root entry command.
 * Uses double-quoted printf for env var expansion; additional_context shape (NOT hookSpecificOutput).
 * GT-3.4 cursor variant.
 */
export const CURSOR_PLUGIN_ROOT_ENTRY = {
  command: `printf '{"additional_context":"Rosetta Plugin Path: %s"}' "\${CURSOR_PROJECT_DIR}"`,
};
